#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : directx-headers
Version  : 1.608.2
Release  : 5
URL      : https://github.com/microsoft/DirectX-Headers/archive/v1.608.2/DirectX-Headers-1.608.2.tar.gz
Source0  : https://github.com/microsoft/DirectX-Headers/archive/v1.608.2/DirectX-Headers-1.608.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: directx-headers-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-meson
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : googletest-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: notest.patch

%description
# DirectX Headers
This repository hosts the official Direct3D 12 headers. These headers are made available under the MIT license rather than the traditional Windows SDK license.

%package dev
Summary: dev components for the directx-headers package.
Group: Development
Provides: directx-headers-devel = %{version}-%{release}
Requires: directx-headers = %{version}-%{release}

%description dev
dev components for the directx-headers package.


%package dev32
Summary: dev32 components for the directx-headers package.
Group: Default
Requires: directx-headers-dev = %{version}-%{release}

%description dev32
dev32 components for the directx-headers package.


%package license
Summary: license components for the directx-headers package.
Group: Default

%description license
license components for the directx-headers package.


%package staticdev
Summary: staticdev components for the directx-headers package.
Group: Default
Requires: directx-headers-dev = %{version}-%{release}

%description staticdev
staticdev components for the directx-headers package.


%package staticdev32
Summary: staticdev32 components for the directx-headers package.
Group: Default
Requires: directx-headers-dev = %{version}-%{release}

%description staticdev32
staticdev32 components for the directx-headers package.


%prep
%setup -q -n DirectX-Headers-1.608.2
cd %{_builddir}/DirectX-Headers-1.608.2
%patch1 -p1
pushd ..
cp -a DirectX-Headers-1.608.2 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1673366617
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dbuild-test=false  builddir
ninja -v -C builddir
pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
meson --libdir=lib32 --prefix=/usr --buildtype=plain -Dbuild-test=false  builddir
ninja -v -C builddir
popd

%install
mkdir -p %{buildroot}/usr/share/package-licenses/directx-headers
cp %{_builddir}/DirectX-Headers-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/directx-headers/18b993cdf002a15456fbd9aa0d42c3576a5c8d2d || :
pushd ../build32/
DESTDIR=%{buildroot} ninja -C builddir install
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/directx/D3D12TokenizedProgramFormat.hpp
/usr/include/directx/d3d12.h
/usr/include/directx/d3d12.idl
/usr/include/directx/d3d12compatibility.h
/usr/include/directx/d3d12compatibility.idl
/usr/include/directx/d3d12sdklayers.h
/usr/include/directx/d3d12sdklayers.idl
/usr/include/directx/d3d12shader.h
/usr/include/directx/d3d12video.h
/usr/include/directx/d3d12video.idl
/usr/include/directx/d3dcommon.h
/usr/include/directx/d3dcommon.idl
/usr/include/directx/d3dx12.h
/usr/include/directx/d3dx12_barriers.h
/usr/include/directx/d3dx12_check_feature_support.h
/usr/include/directx/d3dx12_core.h
/usr/include/directx/d3dx12_default.h
/usr/include/directx/d3dx12_pipeline_state_stream.h
/usr/include/directx/d3dx12_property_format_table.h
/usr/include/directx/d3dx12_render_pass.h
/usr/include/directx/d3dx12_resource_helpers.h
/usr/include/directx/d3dx12_root_signature.h
/usr/include/directx/d3dx12_state_object.h
/usr/include/directx/dxcore.h
/usr/include/directx/dxcore_interface.h
/usr/include/directx/dxgicommon.h
/usr/include/directx/dxgicommon.idl
/usr/include/directx/dxgiformat.h
/usr/include/directx/dxgiformat.idl
/usr/include/dxguids/dxguids.h
/usr/include/wsl/stubs/basetsd.h
/usr/include/wsl/stubs/oaidl.h
/usr/include/wsl/stubs/ocidl.h
/usr/include/wsl/stubs/rpc.h
/usr/include/wsl/stubs/rpcndr.h
/usr/include/wsl/stubs/unknwn.h
/usr/include/wsl/stubs/unknwnbase.h
/usr/include/wsl/stubs/winapifamily.h
/usr/include/wsl/stubs/wrl/client.h
/usr/include/wsl/stubs/wrl/implements.h
/usr/include/wsl/winadapter.h
/usr/include/wsl/wrladapter.h
/usr/lib64/pkgconfig/DirectX-Headers.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/pkgconfig/32DirectX-Headers.pc
/usr/lib32/pkgconfig/DirectX-Headers.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/directx-headers/18b993cdf002a15456fbd9aa0d42c3576a5c8d2d

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libDirectX-Guids.a
/usr/lib64/libd3dx12-format-properties.a

%files staticdev32
%defattr(-,root,root,-)
/usr/lib32/libDirectX-Guids.a
/usr/lib32/libd3dx12-format-properties.a
