#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : directx-headers
Version  : 1.602.0
Release  : 2
URL      : https://github.com/microsoft/DirectX-Headers/archive/refs/tags/v1.602.0.tar.gz
Source0  : https://github.com/microsoft/DirectX-Headers/archive/refs/tags/v1.602.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: directx-headers-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-meson
BuildRequires : googletest-dev
Patch1: notest.patch

%description
# DirectX Headers
This repository hosts the official Direct3D 12 headers. These headers are made available under the MIT license rather than the traditional Windows SDK license.

%package dev
Summary: dev components for the directx-headers package.
Group: Development
Provides: directx-headers-devel = %{version}-%{release}
Requires: directx-headers = %{version}-%{release}

%description dev
dev components for the directx-headers package.


%package license
Summary: license components for the directx-headers package.
Group: Default

%description license
license components for the directx-headers package.


%package staticdev
Summary: staticdev components for the directx-headers package.
Group: Default
Requires: directx-headers-dev = %{version}-%{release}

%description staticdev
staticdev components for the directx-headers package.


%prep
%setup -q -n DirectX-Headers-1.602.0
cd %{_builddir}/DirectX-Headers-1.602.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1657139007
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dbuild-test=false  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/directx-headers
cp %{_builddir}/DirectX-Headers-1.602.0/LICENSE %{buildroot}/usr/share/package-licenses/directx-headers/18b993cdf002a15456fbd9aa0d42c3576a5c8d2d
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/directx/d3d12.h
/usr/include/directx/d3d12.idl
/usr/include/directx/d3d12compatibility.h
/usr/include/directx/d3d12compatibility.idl
/usr/include/directx/d3d12sdklayers.h
/usr/include/directx/d3d12sdklayers.idl
/usr/include/directx/d3d12shader.h
/usr/include/directx/d3d12video.h
/usr/include/directx/d3d12video.idl
/usr/include/directx/d3dcommon.h
/usr/include/directx/d3dcommon.idl
/usr/include/directx/d3dx12.h
/usr/include/directx/dxcore.h
/usr/include/directx/dxcore_interface.h
/usr/include/directx/dxgicommon.h
/usr/include/directx/dxgicommon.idl
/usr/include/directx/dxgiformat.h
/usr/include/directx/dxgiformat.idl
/usr/include/dxguids/dxguids.h
/usr/include/wsl/stubs/OAIdl.h
/usr/include/wsl/stubs/OCIdl.h
/usr/include/wsl/stubs/rpc.h
/usr/include/wsl/stubs/rpcndr.h
/usr/include/wsl/stubs/winapifamily.h
/usr/include/wsl/stubs/wrl/client.h
/usr/include/wsl/stubs/wrl/implements.h
/usr/include/wsl/winadapter.h
/usr/include/wsl/wrladapter.h
/usr/lib64/pkgconfig/DirectX-Headers.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/directx-headers/18b993cdf002a15456fbd9aa0d42c3576a5c8d2d

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libDirectX-Guids.a
